export default [
  {
    code: "AF",
    country: "Afghanistan",
    phoneCode: "93",
    flag: "https://flagcdn.com/w320/af.png",
  },
  {
    code: "AX",
    country: "Aland Islands",
    phoneCode: "+358-18",
    flag: "https://flagcdn.com/w320/ax.png",
  },
  {
    code: "AL",
    country: "Albania",
    phoneCode: "355",
    flag: "https://flagcdn.com/w320/al.png",
  },
  {
    code: "DZ",
    country: "Algeria",
    phoneCode: "213",
    flag: "https://flagcdn.com/w320/dz.png",
  },
  {
    code: "AS",
    country: "American Samoa",
    phoneCode: "+1-684",
    flag: "https://flagcdn.com/w320/as.png",
  },
  {
    code: "AD",
    country: "Andorra",
    phoneCode: "376",
    flag: "https://flagcdn.com/w320/ad.png",
  },
  {
    code: "AO",
    country: "Angola",
    phoneCode: "244",
    flag: "https://flagcdn.com/w320/ao.png",
  },
  {
    code: "AI",
    country: "Anguilla",
    phoneCode: "+1-264",
    flag: "https://flagcdn.com/w320/ai.png",
  },
  {
    code: "AQ",
    country: "Antarctica",
    phoneCode: "",
    flag: "https://flagcdn.com/w320/aq.png",
  },
  {
    code: "AG",
    country: "Antigua and Barbuda",
    phoneCode: "+1-268",
    flag: "https://flagcdn.com/w320/ag.png",
  },
  {
    code: "AR",
    country: "Argentina",
    phoneCode: "54",
    flag: "https://flagcdn.com/w320/ar.png",
  },
  {
    code: "AM",
    country: "Armenia",
    phoneCode: "374",
    flag: "https://flagcdn.com/w320/am.png",
  },
  {
    code: "AW",
    country: "Aruba",
    phoneCode: "297",
    flag: "https://flagcdn.com/w320/aw.png",
  },
  {
    code: "AU",
    country: "Australia",
    phoneCode: "61",
    flag: "https://flagcdn.com/w320/au.png",
  },
  {
    code: "AT",
    country: "Austria",
    phoneCode: "43",
    flag: "https://flagcdn.com/w320/at.png",
  },
  {
    code: "AZ",
    country: "Azerbaijan",
    phoneCode: "994",
    flag: "https://flagcdn.com/w320/az.png",
  },
  {
    code: "BS",
    country: "Bahamas",
    phoneCode: "+1-242",
    flag: "https://flagcdn.com/w320/bs.png",
  },
  {
    code: "BH",
    country: "Bahrain",
    phoneCode: "973",
    flag: "https://flagcdn.com/w320/bh.png",
  },
  {
    code: "BD",
    country: "Bangladesh",
    phoneCode: "880",
    flag: "https://flagcdn.com/w320/bd.png",
  },
  {
    code: "BB",
    country: "Barbados",
    phoneCode: "+1-246",
    flag: "https://flagcdn.com/w320/bb.png",
  },
  {
    code: "BY",
    country: "Belarus",
    phoneCode: "375",
    flag: "https://flagcdn.com/w320/by.png",
  },
  {
    code: "BE",
    country: "Belgium",
    phoneCode: "32",
    flag: "https://flagcdn.com/w320/be.png",
  },
  {
    code: "BZ",
    country: "Belize",
    phoneCode: "501",
    flag: "https://flagcdn.com/w320/bz.png",
  },
  {
    code: "BJ",
    country: "Benin",
    phoneCode: "229",
    flag: "https://flagcdn.com/w320/bj.png",
  },
  {
    code: "BM",
    country: "Bermuda",
    phoneCode: "+1-441",
    flag: "https://flagcdn.com/w320/bm.png",
  },
  {
    code: "BT",
    country: "Bhutan",
    phoneCode: "975",
    flag: "https://flagcdn.com/w320/bt.png",
  },
  {
    code: "BO",
    country: "Bolivia",
    phoneCode: "591",
    flag: "https://flagcdn.com/w320/bo.png",
  },
  {
    code: "BQ",
    country: "Bonaire, Saint Eustatius and Saba ",
    phoneCode: "599",
    flag: "https://flagcdn.com/w320/bq.png",
  },
  {
    code: "BA",
    country: "Bosnia and Herzegovina",
    phoneCode: "387",
    flag: "https://flagcdn.com/w320/ba.png",
  },
  {
    code: "BW",
    country: "Botswana",
    phoneCode: "267",
    flag: "https://flagcdn.com/w320/bw.png",
  },
  {
    code: "BV",
    country: "Bouvet Island",
    phoneCode: "",
    flag: "https://flagcdn.com/w320/bv.png",
  },
  {
    code: "BR",
    country: "Brazil",
    phoneCode: "55",
    flag: "https://flagcdn.com/w320/br.png",
  },
  {
    code: "IO",
    country: "British Indian Ocean Territory",
    phoneCode: "246",
    flag: "https://flagcdn.com/w320/io.png",
  },
  {
    code: "VG",
    country: "British Virgin Islands",
    phoneCode: "+1-284",
    flag: "https://flagcdn.com/w320/vg.png",
  },
  {
    code: "BN",
    country: "Brunei",
    phoneCode: "673",
    flag: "https://flagcdn.com/w320/bn.png",
  },
  {
    code: "BG",
    country: "Bulgaria",
    phoneCode: "359",
    flag: "https://flagcdn.com/w320/bg.png",
  },
  {
    code: "BF",
    country: "Burkina Faso",
    phoneCode: "226",
    flag: "https://flagcdn.com/w320/bf.png",
  },
  {
    code: "BI",
    country: "Burundi",
    phoneCode: "257",
    flag: "https://flagcdn.com/w320/bi.png",
  },
  {
    code: "KH",
    country: "Cambodia",
    phoneCode: "855",
    flag: "https://flagcdn.com/w320/kh.png",
  },
  {
    code: "CM",
    country: "Cameroon",
    phoneCode: "237",
    flag: "https://flagcdn.com/w320/cm.png",
  },
  {
    code: "CA",
    country: "Canada",
    phoneCode: "1",
    flag: "https://flagcdn.com/w320/ca.png",
  },
  {
    code: "CV",
    country: "Cape Verde",
    phoneCode: "238",
    flag: "https://flagcdn.com/w320/cv.png",
  },
  {
    code: "KY",
    country: "Cayman Islands",
    phoneCode: "+1-345",
    flag: "https://flagcdn.com/w320/ky.png",
  },
  {
    code: "CF",
    country: "Central African Republic",
    phoneCode: "236",
    flag: "https://flagcdn.com/w320/cf.png",
  },
  {
    code: "TD",
    country: "Chad",
    phoneCode: "235",
    flag: "https://flagcdn.com/w320/td.png",
  },
  {
    code: "CL",
    country: "Chile",
    phoneCode: "56",
    flag: "https://flagcdn.com/w320/cl.png",
  },
  {
    code: "CN",
    country: "China",
    phoneCode: "86",
    flag: "https://flagcdn.com/w320/cn.png",
  },
  {
    code: "CX",
    country: "Christmas Island",
    phoneCode: "61",
    flag: "https://flagcdn.com/w320/cx.png",
  },
  {
    code: "CC",
    country: "Cocos Islands",
    phoneCode: "61",
    flag: "https://flagcdn.com/w320/cc.png",
  },
  {
    code: "CO",
    country: "Colombia",
    phoneCode: "57",
    flag: "https://flagcdn.com/w320/co.png",
  },
  {
    code: "KM",
    country: "Comoros",
    phoneCode: "269",
    flag: "https://flagcdn.com/w320/km.png",
  },
  {
    code: "CK",
    country: "Cook Islands",
    phoneCode: "682",
    flag: "https://flagcdn.com/w320/ck.png",
  },
  {
    code: "CR",
    country: "Costa Rica",
    phoneCode: "506",
    flag: "https://flagcdn.com/w320/cr.png",
  },
  {
    code: "HR",
    country: "Croatia",
    phoneCode: "385",
    flag: "https://flagcdn.com/w320/hr.png",
  },
  {
    code: "CU",
    country: "Cuba",
    phoneCode: "53",
    flag: "https://flagcdn.com/w320/cu.png",
  },
  {
    code: "CW",
    country: "Curacao",
    phoneCode: "599",
    flag: "https://flagcdn.com/w320/cw.png",
  },
  {
    code: "CY",
    country: "Cyprus",
    phoneCode: "357",
    flag: "https://flagcdn.com/w320/cy.png",
  },
  {
    code: "CZ",
    country: "Czech Republic",
    phoneCode: "420",
    flag: "https://flagcdn.com/w320/cz.png",
  },
  {
    code: "CD",
    country: "Democratic Republic of the Congo",
    phoneCode: "243",
    flag: "https://flagcdn.com/w320/cd.png",
  },
  {
    code: "DK",
    country: "Denmark",
    phoneCode: "45",
    flag: "https://flagcdn.com/w320/dk.png",
  },
  {
    code: "DJ",
    country: "Djibouti",
    phoneCode: "253",
    flag: "https://flagcdn.com/w320/dj.png",
  },
  {
    code: "DM",
    country: "Dominica",
    phoneCode: "+1-767",
    flag: "https://flagcdn.com/w320/dm.png",
  },
  {
    code: "DO",
    country: "Dominican Republic",
    phoneCode: "+1-809 and 1-829",
    flag: "https://flagcdn.com/w320/do.png",
  },
  {
    code: "TL",
    country: "East Timor",
    phoneCode: "670",
    flag: "https://flagcdn.com/w320/tl.png",
  },
  {
    code: "EC",
    country: "Ecuador",
    phoneCode: "593",
    flag: "https://flagcdn.com/w320/ec.png",
  },
  {
    code: "EG",
    country: "Egypt",
    phoneCode: "20",
    flag: "https://flagcdn.com/w320/eg.png",
  },
  {
    code: "SV",
    country: "El Salvador",
    phoneCode: "503",
    flag: "https://flagcdn.com/w320/sv.png",
  },
  {
    code: "GQ",
    country: "Equatorial Guinea",
    phoneCode: "240",
    flag: "https://flagcdn.com/w320/gq.png",
  },
  {
    code: "ER",
    country: "Eritrea",
    phoneCode: "291",
    flag: "https://flagcdn.com/w320/er.png",
  },
  {
    code: "EE",
    country: "Estonia",
    phoneCode: "372",
    flag: "https://flagcdn.com/w320/ee.png",
  },
  {
    code: "ET",
    country: "Ethiopia",
    phoneCode: "251",
    flag: "https://flagcdn.com/w320/et.png",
  },
  {
    code: "FK",
    country: "Falkland Islands",
    phoneCode: "500",
    flag: "https://flagcdn.com/w320/fk.png",
  },
  {
    code: "FO",
    country: "Faroe Islands",
    phoneCode: "298",
    flag: "https://flagcdn.com/w320/fo.png",
  },
  {
    code: "FJ",
    country: "Fiji",
    phoneCode: "679",
    flag: "https://flagcdn.com/w320/fj.png",
  },
  {
    code: "FI",
    country: "Finland",
    phoneCode: "358",
    flag: "https://flagcdn.com/w320/fi.png",
  },
  {
    code: "FR",
    country: "France",
    phoneCode: "33",
    flag: "https://flagcdn.com/w320/fr.png",
  },
  {
    code: "GF",
    country: "French Guiana",
    phoneCode: "594",
    flag: "https://flagcdn.com/w320/gf.png",
  },
  {
    code: "PF",
    country: "French Polynesia",
    phoneCode: "689",
    flag: "https://flagcdn.com/w320/pf.png",
  },
  {
    code: "TF",
    country: "French Southern Territories",
    phoneCode: "",
    flag: "https://flagcdn.com/w320/tf.png",
  },
  {
    code: "GA",
    country: "Gabon",
    phoneCode: "241",
    flag: "https://flagcdn.com/w320/ga.png",
  },
  {
    code: "GM",
    country: "Gambia",
    phoneCode: "220",
    flag: "https://flagcdn.com/w320/gm.png",
  },
  {
    code: "GE",
    country: "Georgia",
    phoneCode: "995",
    flag: "https://flagcdn.com/w320/ge.png",
  },
  {
    code: "DE",
    country: "Germany",
    phoneCode: "49",
    flag: "https://flagcdn.com/w320/de.png",
  },
  {
    code: "GH",
    country: "Ghana",
    phoneCode: "233",
    flag: "https://flagcdn.com/w320/gh.png",
  },
  {
    code: "GI",
    country: "Gibraltar",
    phoneCode: "350",
    flag: "https://flagcdn.com/w320/gi.png",
  },
  {
    code: "GR",
    country: "Greece",
    phoneCode: "30",
    flag: "https://flagcdn.com/w320/gr.png",
  },
  {
    code: "GL",
    country: "Greenland",
    phoneCode: "299",
    flag: "https://flagcdn.com/w320/gl.png",
  },
  {
    code: "GD",
    country: "Grenada",
    phoneCode: "+1-473",
    flag: "https://flagcdn.com/w320/gd.png",
  },
  {
    code: "GP",
    country: "Guadeloupe",
    phoneCode: "590",
    flag: "https://flagcdn.com/w320/gp.png",
  },
  {
    code: "GU",
    country: "Guam",
    phoneCode: "+1-671",
    flag: "https://flagcdn.com/w320/gu.png",
  },
  {
    code: "GT",
    country: "Guatemala",
    phoneCode: "502",
    flag: "https://flagcdn.com/w320/gt.png",
  },
  {
    code: "GG",
    country: "Guernsey",
    phoneCode: "+44-1481",
    flag: "https://flagcdn.com/w320/gg.png",
  },
  {
    code: "GN",
    country: "Guinea",
    phoneCode: "224",
    flag: "https://flagcdn.com/w320/gn.png",
  },
  {
    code: "GW",
    country: "Guinea-Bissau",
    phoneCode: "245",
    flag: "https://flagcdn.com/w320/gw.png",
  },
  {
    code: "GY",
    country: "Guyana",
    phoneCode: "592",
    flag: "https://flagcdn.com/w320/gy.png",
  },
  {
    code: "HT",
    country: "Haiti",
    phoneCode: "509",
    flag: "https://flagcdn.com/w320/ht.png",
  },
  {
    code: "HM",
    country: "Heard Island and McDonald Islands",
    phoneCode: " ",
    flag: "https://flagcdn.com/w320/hm.png",
  },
  {
    code: "HN",
    country: "Honduras",
    phoneCode: "504",
    flag: "https://flagcdn.com/w320/hn.png",
  },
  {
    code: "HK",
    country: "Hong Kong",
    phoneCode: "852",
    flag: "https://flagcdn.com/w320/hk.png",
  },
  {
    code: "HU",
    country: "Hungary",
    phoneCode: "36",
    flag: "https://flagcdn.com/w320/hu.png",
  },
  {
    code: "IS",
    country: "Iceland",
    phoneCode: "354",
    flag: "https://flagcdn.com/w320/is.png",
  },
  {
    code: "IN",
    country: "India",
    phoneCode: "91",
    flag: "https://flagcdn.com/w320/in.png",
  },
  {
    code: "ID",
    country: "Indonesia",
    phoneCode: "62",
    flag: "https://flagcdn.com/w320/id.png",
  },
  {
    code: "IR",
    country: "Iran",
    phoneCode: "98",
    flag: "https://flagcdn.com/w320/ir.png",
  },
  {
    code: "IQ",
    country: "Iraq",
    phoneCode: "964",
    flag: "https://flagcdn.com/w320/iq.png",
  },
  {
    code: "IE",
    country: "Ireland",
    phoneCode: "353",
    flag: "https://flagcdn.com/w320/ie.png",
  },
  {
    code: "IM",
    country: "Isle of Man",
    phoneCode: "+44-1624",
    flag: "https://flagcdn.com/w320/im.png",
  },
  {
    code: "IL",
    country: "Israel",
    phoneCode: "972",
    flag: "https://flagcdn.com/w320/il.png",
  },
  {
    code: "IT",
    country: "Italy",
    phoneCode: "39",
    flag: "https://flagcdn.com/w320/it.png",
  },
  {
    code: "CI",
    country: "Ivory Coast",
    phoneCode: "225",
    flag: "https://flagcdn.com/w320/ci.png",
  },
  {
    code: "JM",
    country: "Jamaica",
    phoneCode: "+1-876",
    flag: "https://flagcdn.com/w320/jm.png",
  },
  {
    code: "JP",
    country: "Japan",
    phoneCode: "81",
    flag: "https://flagcdn.com/w320/jp.png",
  },
  {
    code: "JE",
    country: "Jersey",
    phoneCode: "+44-1534",
    flag: "https://flagcdn.com/w320/je.png",
  },
  {
    code: "JO",
    country: "Jordan",
    phoneCode: "962",
    flag: "https://flagcdn.com/w320/jo.png",
  },
  {
    code: "KZ",
    country: "Kazakhstan",
    phoneCode: "7",
    flag: "https://flagcdn.com/w320/kz.png",
  },
  {
    code: "KE",
    country: "Kenya",
    phoneCode: "254",
    flag: "https://flagcdn.com/w320/ke.png",
  },
  {
    code: "KI",
    country: "Kiribati",
    phoneCode: "686",
    flag: "https://flagcdn.com/w320/ki.png",
  },
  {
    code: "XK",
    country: "Kosovo",
    phoneCode: "",
    flag: "https://flagcdn.com/w320/xk.png",
  },
  {
    code: "KW",
    country: "Kuwait",
    phoneCode: "965",
    flag: "https://flagcdn.com/w320/kw.png",
  },
  {
    code: "KG",
    country: "Kyrgyzstan",
    phoneCode: "996",
    flag: "https://flagcdn.com/w320/kg.png",
  },
  {
    code: "LA",
    country: "Laos",
    phoneCode: "856",
    flag: "https://flagcdn.com/w320/la.png",
  },
  {
    code: "LV",
    country: "Latvia",
    phoneCode: "371",
    flag: "https://flagcdn.com/w320/lv.png",
  },
  {
    code: "LB",
    country: "Lebanon",
    phoneCode: "961",
    flag: "https://flagcdn.com/w320/lb.png",
  },
  {
    code: "LS",
    country: "Lesotho",
    phoneCode: "266",
    flag: "https://flagcdn.com/w320/ls.png",
  },
  {
    code: "LR",
    country: "Liberia",
    phoneCode: "231",
    flag: "https://flagcdn.com/w320/lr.png",
  },
  {
    code: "LY",
    country: "Libya",
    phoneCode: "218",
    flag: "https://flagcdn.com/w320/ly.png",
  },
  {
    code: "LI",
    country: "Liechtenstein",
    phoneCode: "423",
    flag: "https://flagcdn.com/w320/li.png",
  },
  {
    code: "LT",
    country: "Lithuania",
    phoneCode: "370",
    flag: "https://flagcdn.com/w320/lt.png",
  },
  {
    code: "LU",
    country: "Luxembourg",
    phoneCode: "352",
    flag: "https://flagcdn.com/w320/lu.png",
  },
  {
    code: "MO",
    country: "Macao",
    phoneCode: "853",
    flag: "https://flagcdn.com/w320/mo.png",
  },
  {
    code: "MK",
    country: "Macedonia",
    phoneCode: "389",
    flag: "https://flagcdn.com/w320/mk.png",
  },
  {
    code: "MG",
    country: "Madagascar",
    phoneCode: "261",
    flag: "https://flagcdn.com/w320/mg.png",
  },
  {
    code: "MW",
    country: "Malawi",
    phoneCode: "265",
    flag: "https://flagcdn.com/w320/mw.png",
  },
  {
    code: "MY",
    country: "Malaysia",
    phoneCode: "60",
    flag: "https://flagcdn.com/w320/my.png",
  },
  {
    code: "MV",
    country: "Maldives",
    phoneCode: "960",
    flag: "https://flagcdn.com/w320/mv.png",
  },
  {
    code: "ML",
    country: "Mali",
    phoneCode: "223",
    flag: "https://flagcdn.com/w320/ml.png",
  },
  {
    code: "MT",
    country: "Malta",
    phoneCode: "356",
    flag: "https://flagcdn.com/w320/mt.png",
  },
  {
    code: "MH",
    country: "Marshall Islands",
    phoneCode: "692",
    flag: "https://flagcdn.com/w320/mh.png",
  },
  {
    code: "MQ",
    country: "Martinique",
    phoneCode: "596",
    flag: "https://flagcdn.com/w320/mq.png",
  },
  {
    code: "MR",
    country: "Mauritania",
    phoneCode: "222",
    flag: "https://flagcdn.com/w320/mr.png",
  },
  {
    code: "MU",
    country: "Mauritius",
    phoneCode: "230",
    flag: "https://flagcdn.com/w320/mu.png",
  },
  {
    code: "YT",
    country: "Mayotte",
    phoneCode: "262",
    flag: "https://flagcdn.com/w320/yt.png",
  },
  {
    code: "MX",
    country: "Mexico",
    phoneCode: "52",
    flag: "https://flagcdn.com/w320/mx.png",
  },
  {
    code: "FM",
    country: "Micronesia",
    phoneCode: "691",
    flag: "https://flagcdn.com/w320/fm.png",
  },
  {
    code: "MD",
    country: "Moldova",
    phoneCode: "373",
    flag: "https://flagcdn.com/w320/md.png",
  },
  {
    code: "MC",
    country: "Monaco",
    phoneCode: "377",
    flag: "https://flagcdn.com/w320/mc.png",
  },
  {
    code: "MN",
    country: "Mongolia",
    phoneCode: "976",
    flag: "https://flagcdn.com/w320/mn.png",
  },
  {
    code: "ME",
    country: "Montenegro",
    phoneCode: "382",
    flag: "https://flagcdn.com/w320/me.png",
  },
  {
    code: "MS",
    country: "Montserrat",
    phoneCode: "+1-664",
    flag: "https://flagcdn.com/w320/ms.png",
  },
  {
    code: "MA",
    country: "Morocco",
    phoneCode: "212",
    flag: "https://flagcdn.com/w320/ma.png",
  },
  {
    code: "MZ",
    country: "Mozambique",
    phoneCode: "258",
    flag: "https://flagcdn.com/w320/mz.png",
  },
  {
    code: "MM",
    country: "Myanmar",
    phoneCode: "95",
    flag: "https://flagcdn.com/w320/mm.png",
  },
  {
    code: "NA",
    country: "Namibia",
    phoneCode: "264",
    flag: "https://flagcdn.com/w320/na.png",
  },
  {
    code: "NR",
    country: "Nauru",
    phoneCode: "674",
    flag: "https://flagcdn.com/w320/nr.png",
  },
  {
    code: "NP",
    country: "Nepal",
    phoneCode: "977",
    flag: "https://flagcdn.com/w320/np.png",
  },
  {
    code: "NL",
    country: "Netherlands",
    phoneCode: "31",
    flag: "https://flagcdn.com/w320/nl.png",
  },
  {
    code: "NC",
    country: "New Caledonia",
    phoneCode: "687",
    flag: "https://flagcdn.com/w320/nc.png",
  },
  {
    code: "NZ",
    country: "New Zealand",
    phoneCode: "64",
    flag: "https://flagcdn.com/w320/nz.png",
  },
  {
    code: "NI",
    country: "Nicaragua",
    phoneCode: "505",
    flag: "https://flagcdn.com/w320/ni.png",
  },
  {
    code: "NE",
    country: "Niger",
    phoneCode: "227",
    flag: "https://flagcdn.com/w320/ne.png",
  },
  {
    code: "NG",
    country: "Nigeria",
    phoneCode: "234",
    flag: "https://flagcdn.com/w320/ng.png",
  },
  {
    code: "NU",
    country: "Niue",
    phoneCode: "683",
    flag: "https://flagcdn.com/w320/nu.png",
  },
  {
    code: "NF",
    country: "Norfolk Island",
    phoneCode: "672",
    flag: "https://flagcdn.com/w320/nf.png",
  },
  {
    code: "KP",
    country: "North Korea",
    phoneCode: "850",
    flag: "https://flagcdn.com/w320/kp.png",
  },
  {
    code: "MP",
    country: "Northern Mariana Islands",
    phoneCode: "+1-670",
    flag: "https://flagcdn.com/w320/mp.png",
  },
  {
    code: "NO",
    country: "Norway",
    phoneCode: "47",
    flag: "https://flagcdn.com/w320/no.png",
  },
  {
    code: "OM",
    country: "Oman",
    phoneCode: "968",
    flag: "https://flagcdn.com/w320/om.png",
  },
  {
    code: "PK",
    country: "Pakistan",
    phoneCode: "92",
    flag: "https://flagcdn.com/w320/pk.png",
  },
  {
    code: "PW",
    country: "Palau",
    phoneCode: "680",
    flag: "https://flagcdn.com/w320/pw.png",
  },
  {
    code: "PS",
    country: "Palestinian Territory",
    phoneCode: "970",
    flag: "https://flagcdn.com/w320/ps.png",
  },
  {
    code: "PA",
    country: "Panama",
    phoneCode: "507",
    flag: "https://flagcdn.com/w320/pa.png",
  },
  {
    code: "PG",
    country: "Papua New Guinea",
    phoneCode: "675",
    flag: "https://flagcdn.com/w320/pg.png",
  },
  {
    code: "PY",
    country: "Paraguay",
    phoneCode: "595",
    flag: "https://flagcdn.com/w320/py.png",
  },
  {
    code: "PE",
    country: "Peru",
    phoneCode: "51",
    flag: "https://flagcdn.com/w320/pe.png",
  },
  {
    code: "PH",
    country: "Philippines",
    phoneCode: "63",
    flag: "https://flagcdn.com/w320/ph.png",
  },
  {
    code: "PN",
    country: "Pitcairn",
    phoneCode: "870",
    flag: "https://flagcdn.com/w320/pn.png",
  },
  {
    code: "PL",
    country: "Poland",
    phoneCode: "48",
    flag: "https://flagcdn.com/w320/pl.png",
  },
  {
    code: "PT",
    country: "Portugal",
    phoneCode: "351",
    flag: "https://flagcdn.com/w320/pt.png",
  },
  {
    code: "PR",
    country: "Puerto Rico",
    phoneCode: "+1-787 and 1-939",
    flag: "https://flagcdn.com/w320/pr.png",
  },
  {
    code: "QA",
    country: "Qatar",
    phoneCode: "974",
    flag: "https://flagcdn.com/w320/qa.png",
  },
  {
    code: "CG",
    country: "Republic of the Congo",
    phoneCode: "242",
    flag: "https://flagcdn.com/w320/cg.png",
  },
  {
    code: "RE",
    country: "Reunion",
    phoneCode: "262",
    flag: "https://flagcdn.com/w320/re.png",
  },
  {
    code: "RO",
    country: "Romania",
    phoneCode: "40",
    flag: "https://flagcdn.com/w320/ro.png",
  },
  {
    code: "RU",
    country: "Russia",
    phoneCode: "7",
    flag: "https://flagcdn.com/w320/ru.png",
  },
  {
    code: "RW",
    country: "Rwanda",
    phoneCode: "250",
    flag: "https://flagcdn.com/w320/rw.png",
  },
  {
    code: "BL",
    country: "Saint Barthelemy",
    phoneCode: "590",
    flag: "https://flagcdn.com/w320/bl.png",
  },
  {
    code: "SH",
    country: "Saint Helena",
    phoneCode: "290",
    flag: "https://flagcdn.com/w320/sh.png",
  },
  {
    code: "KN",
    country: "Saint Kitts and Nevis",
    phoneCode: "+1-869",
    flag: "https://flagcdn.com/w320/kn.png",
  },
  {
    code: "LC",
    country: "Saint Lucia",
    phoneCode: "+1-758",
    flag: "https://flagcdn.com/w320/lc.png",
  },
  {
    code: "MF",
    country: "Saint Martin",
    phoneCode: "590",
    flag: "https://flagcdn.com/w320/mf.png",
  },
  {
    code: "PM",
    country: "Saint Pierre and Miquelon",
    phoneCode: "508",
    flag: "https://flagcdn.com/w320/pm.png",
  },
  {
    code: "VC",
    country: "Saint Vincent and the Grenadines",
    phoneCode: "+1-784",
    flag: "https://flagcdn.com/w320/vc.png",
  },
  {
    code: "WS",
    country: "Samoa",
    phoneCode: "685",
    flag: "https://flagcdn.com/w320/ws.png",
  },
  {
    code: "SM",
    country: "San Marino",
    phoneCode: "378",
    flag: "https://flagcdn.com/w320/sm.png",
  },
  {
    code: "ST",
    country: "Sao Tome and Principe",
    phoneCode: "239",
    flag: "https://flagcdn.com/w320/st.png",
  },
  {
    code: "SA",
    country: "Saudi Arabia",
    phoneCode: "966",
    flag: "https://flagcdn.com/w320/sa.png",
  },
  {
    code: "SN",
    country: "Senegal",
    phoneCode: "221",
    flag: "https://flagcdn.com/w320/sn.png",
  },
  {
    code: "RS",
    country: "Serbia",
    phoneCode: "381",
    flag: "https://flagcdn.com/w320/rs.png",
  },
  {
    code: "SC",
    country: "Seychelles",
    phoneCode: "248",
    flag: "https://flagcdn.com/w320/sc.png",
  },
  {
    code: "SL",
    country: "Sierra Leone",
    phoneCode: "232",
    flag: "https://flagcdn.com/w320/sl.png",
  },
  {
    code: "SG",
    country: "Singapore",
    phoneCode: "65",
    flag: "https://flagcdn.com/w320/sg.png",
  },
  {
    code: "SX",
    country: "Sint Maarten",
    phoneCode: "599",
    flag: "https://flagcdn.com/w320/sx.png",
  },
  {
    code: "SK",
    country: "Slovakia",
    phoneCode: "421",
    flag: "https://flagcdn.com/w320/sk.png",
  },
  {
    code: "SI",
    country: "Slovenia",
    phoneCode: "386",
    flag: "https://flagcdn.com/w320/si.png",
  },
  {
    code: "SB",
    country: "Solomon Islands",
    phoneCode: "677",
    flag: "https://flagcdn.com/w320/sb.png",
  },
  {
    code: "SO",
    country: "Somalia",
    phoneCode: "252",
    flag: "https://flagcdn.com/w320/so.png",
  },
  {
    code: "ZA",
    country: "South Africa",
    phoneCode: "27",
    flag: "https://flagcdn.com/w320/za.png",
  },
  {
    code: "GS",
    country: "South Georgia and the South Sandwich Islands",
    phoneCode: "",
    flag: "https://flagcdn.com/w320/gs.png",
  },
  {
    code: "KR",
    country: "South Korea",
    phoneCode: "82",
    flag: "https://flagcdn.com/w320/kr.png",
  },
  {
    code: "SS",
    country: "South Sudan",
    phoneCode: "211",
    flag: "https://flagcdn.com/w320/ss.png",
  },
  {
    code: "ES",
    country: "Spain",
    phoneCode: "34",
    flag: "https://flagcdn.com/w320/es.png",
  },
  {
    code: "LK",
    country: "Sri Lanka",
    phoneCode: "94",
    flag: "https://flagcdn.com/w320/lk.png",
  },
  {
    code: "SD",
    country: "Sudan",
    phoneCode: "249",
    flag: "https://flagcdn.com/w320/sd.png",
  },
  {
    code: "SR",
    country: "Suriname",
    phoneCode: "597",
    flag: "https://flagcdn.com/w320/sr.png",
  },
  {
    code: "SJ",
    country: "Svalbard and Jan Mayen",
    phoneCode: "47",
    flag: "https://flagcdn.com/w320/sj.png",
  },
  {
    code: "SZ",
    country: "Swaziland",
    phoneCode: "268",
    flag: "https://flagcdn.com/w320/sz.png",
  },
  {
    code: "SE",
    country: "Sweden",
    phoneCode: "46",
    flag: "https://flagcdn.com/w320/se.png",
  },
  {
    code: "CH",
    country: "Switzerland",
    phoneCode: "41",
    flag: "https://flagcdn.com/w320/ch.png",
  },
  {
    code: "SY",
    country: "Syria",
    phoneCode: "963",
    flag: "https://flagcdn.com/w320/sy.png",
  },
  {
    code: "TW",
    country: "Taiwan",
    phoneCode: "886",
    flag: "https://flagcdn.com/w320/tw.png",
  },
  {
    code: "TJ",
    country: "Tajikistan",
    phoneCode: "992",
    flag: "https://flagcdn.com/w320/tj.png",
  },
  {
    code: "TZ",
    country: "Tanzania",
    phoneCode: "255",
    flag: "https://flagcdn.com/w320/tz.png",
  },
  {
    code: "TH",
    country: "Thailand",
    phoneCode: "66",
    flag: "https://flagcdn.com/w320/th.png",
  },
  {
    code: "TG",
    country: "Togo",
    phoneCode: "228",
    flag: "https://flagcdn.com/w320/tg.png",
  },
  {
    code: "TK",
    country: "Tokelau",
    phoneCode: "690",
    flag: "https://flagcdn.com/w320/tk.png",
  },
  {
    code: "TO",
    country: "Tonga",
    phoneCode: "676",
    flag: "https://flagcdn.com/w320/to.png",
  },
  {
    code: "TT",
    country: "Trinidad and Tobago",
    phoneCode: "+1-868",
    flag: "https://flagcdn.com/w320/tt.png",
  },
  {
    code: "TN",
    country: "Tunisia",
    phoneCode: "216",
    flag: "https://flagcdn.com/w320/tn.png",
  },
  {
    code: "TR",
    country: "Turkey",
    phoneCode: "90",
    flag: "https://flagcdn.com/w320/tr.png",
  },
  {
    code: "TM",
    country: "Turkmenistan",
    phoneCode: "993",
    flag: "https://flagcdn.com/w320/tm.png",
  },
  {
    code: "TC",
    country: "Turks and Caicos Islands",
    phoneCode: "+1-649",
    flag: "https://flagcdn.com/w320/tc.png",
  },
  {
    code: "TV",
    country: "Tuvalu",
    phoneCode: "688",
    flag: "https://flagcdn.com/w320/tv.png",
  },
  {
    code: "VI",
    country: "U.S. Virgin Islands",
    phoneCode: "+1-340",
    flag: "https://flagcdn.com/w320/vi.png",
  },
  {
    code: "UG",
    country: "Uganda",
    phoneCode: "256",
    flag: "https://flagcdn.com/w320/ug.png",
  },
  {
    code: "UA",
    country: "Ukraine",
    phoneCode: "380",
    flag: "https://flagcdn.com/w320/ua.png",
  },
  {
    code: "AE",
    country: "United Arab Emirates",
    phoneCode: "971",
    flag: "https://flagcdn.com/w320/ae.png",
  },
  {
    code: "GB",
    country: "United Kingdom",
    phoneCode: "44",
    flag: "https://flagcdn.com/w320/gb.png",
  },
  {
    code: "US",
    country: "United States",
    phoneCode: "1",
    flag: "https://flagcdn.com/w320/us.png",
  },
  {
    code: "UM",
    country: "United States Minor Outlying Islands",
    phoneCode: "1",
    flag: "https://flagcdn.com/w320/um.png",
  },
  {
    code: "UY",
    country: "Uruguay",
    phoneCode: "598",
    flag: "https://flagcdn.com/w320/uy.png",
  },
  {
    code: "UZ",
    country: "Uzbekistan",
    phoneCode: "998",
    flag: "https://flagcdn.com/w320/uz.png",
  },
  {
    code: "VU",
    country: "Vanuatu",
    phoneCode: "678",
    flag: "https://flagcdn.com/w320/vu.png",
  },
  {
    code: "VA",
    country: "Vatican",
    phoneCode: "379",
    flag: "https://flagcdn.com/w320/va.png",
  },
  {
    code: "VE",
    country: "Venezuela",
    phoneCode: "58",
    flag: "https://flagcdn.com/w320/ve.png",
  },
  {
    code: "VN",
    country: "Vietnam",
    phoneCode: "84",
    flag: "https://flagcdn.com/w320/vn.png",
  },
  {
    code: "WF",
    country: "Wallis and Futuna",
    phoneCode: "681",
    flag: "https://flagcdn.com/w320/wf.png",
  },
  {
    code: "EH",
    country: "Western Sahara",
    phoneCode: "212",
    flag: "https://flagcdn.com/w320/eh.png",
  },
  {
    code: "YE",
    country: "Yemen",
    phoneCode: "967",
    flag: "https://flagcdn.com/w320/ye.png",
  },
  {
    code: "ZM",
    country: "Zambia",
    phoneCode: "260",
    flag: "https://flagcdn.com/w320/zm.png",
  },
  {
    code: "ZW",
    country: "Zimbabwe",
    phoneCode: "263",
    flag: "https://flagcdn.com/w320/zw.png",
  },
]