export interface ClaimsActionsCreateModel {
    company_id: number,
    tycker_symbol?: string,
    company_name?: string,
    exchange?: string,
    lawsuit_type?: string,
    eligibility?: string,
    start_eligibility_date: string,
    final_eligibility_date: string,
    potencial_claim?: string,
    total_settlement_fund?: string,
    filing_date?: string,
    claim_deadline?: string,
    law_firm_handing_case?: string,
    case_docket_number?: string,
    value_per_share: number,
    jurisdiction?: string,
    claim_status?: string,
    claim_format_name: string,
    method_send_claim_format: string,
    email: string,
    official_claim_filing_link?: string,
    last_update?: string
}